### ISSUE TITLE
Emilia Sherifova - KKR CIO

### ISSUE THREAD

**Issue by aflies1** [promazo/ProMazo-Videos#13]
https://drive.google.com/drive/folders/1EJ-JLXJCxvqtYCfZhIPS7iE5nI4CfJyh

For this video can we do a broadcast type feel where we have all 3 on-screen and then switch in and out to the one who is speaking?

**Comment by aflies1** [comment]
https://promazo.monday.com/boards/693049887/pulses/693050107

**Comment by vbongard** [comment]
Hi Adam, 

I've finished the video pitch! Sorry again about the call this afternoon, I spent two hours on the phone with the internet company in the morning, things were working fine, then at 4:40 everything fell apart again. It's working now, so hopefully that lasts! Pitch is copy and pasted as well as linked below

Video 1: career exploration
* 6:40 (answering question, how did you work up the courage to change paths?) - not everyone is lucky enough to have a passion or know what they want to do. Be curious, try different things, and you’ll find your passion. 7:22 she starts a personal anecdote about how she balanced her need for technical skills in order to get a visa with her interest in journalism back in the Soviet Union. Ends at 10:12. Love this!!!
* 10:56 - (answering question about the best way to best explore even within a rigid job position) if you prove yourself as someone who gets something done, you have more flexibility and it will take you far. Example: extreme sense of ownership over a project is better than someone who is just a cog in the machine. Short and sweet. Ends at 11:56. Good!!
* 12:26 - “there are a lot of smart people, there aren’t a lot of people who actually get things done.” Ends 12:33. Would pair well with above point
* 14:59 - (Answering question about the experience of going from a big company to a small company/start up) switching companies allowed her to figure out what she enjoys but also allowed her to become very competitive in terms of job apps. Firms want to see people who have varied experiences. Latter half gets into specifics of engineering and firms so may be less relevant. Whole thing ends at 17:24. Great!!

Video 2: short video (less than 2 mins) about the professional role of engineers now and into the future
* 29:47 - (answering question about what the future is like for engineers) Nowadays, most companies are run by engineers, though it wasn’t like this two decades ago. Now, companies like KKR are both world class financial orgs and world class engineering orgs. Tech is necessary for all businesses. Ends 31:42. Not bad! I think could be a good standalone piece focused on engineering and its modern importance.

Video 3: short video (approx two mins) about the role of mentorship in her career path and advice for students seeking mentorship
* 32:05 - (answering question about how mentorship has played a role in her career and how people can find a mentor) avail yourself to different opportunities,  different people, different advice, etc., and make sure that comes from a diverse set of people. Ends 33:28. Could be good for a short standalone on mentorship

https://docs.google.com/document/d/1alVWiKcjYlUk10R1Ukb0JeCOLLwag8vQ7gDbd4lvHn0/edit?usp=sharing

**Comment by vbongard** [comment]
Hi Adam,

I went ahead and put together the videos! If you have feedback on content, please let me know. I can add some graphics and fun quotes and whatnot, but didn't want to take the time to do that yet until I got a sign off on pitch/content. Thanks!

Video 1: https://drive.google.com/file/d/1OVkqUipvvkW4SWinetiPqY8ub4lB3J2y/view?usp=sharing

Video 2: https://drive.google.com/file/d/1ZC2BjHvSSr8pWvPymqDzFKo2rz77vdfc/view?usp=sharing

Video 3: https://drive.google.com/file/d/1Vm7MxKJCGgK28_DcaPshxPzqM1d2ZMH0/view?usp=sharing

**Comment by aflies1** [comment]
@vbongard Waiting for Brett's feedback. I like the content of those. I also think because of the zoom they play better separated than put together.

**Comment by vbongard** [comment]
Hi Adam,

Sorry for the delay! Updated cuts:

Vid 1 cut 2 (added words on screen, slight cropping): https://drive.google.com/file/d/1Awgf5JJH-XCFeQCiIvKJsHQzio9jBQVg/view?usp=sharing
Vid 2 cut 2 (slight cropping): https://drive.google.com/file/d/1hcp_sWGj82NdK0zk2rYeEdQaMKcCEgg2/view?usp=sharing
Vid 3 cut 2 (added words on screen, slight cropping): https://drive.google.com/file/d/1PlK2fmL360GyZOKlN5gfsT_oGPjSt93f/view?usp=sharing

**Comment by jaahmuhl** [comment]
@vbongard 
@aflies1 
Vid 1:
How do you cultivate professional development opportunities?
There were big gaps in the video where the screen goes black (I don't know if you were planning on putting questions in those places)

Vid 2:
00:07-the word course is misspelled
Vid 3:
00:08-Change text to Why are mentors important?

**Comment by vbongard** [comment]
@jaahmuhl @aflies1 

Hi Brett,

Can do for videos 2 and 3! For video 1, it should end at the 2:15 mark. The first cut was the right, but I forgot to chop the second cut at the right point. Will upload adjusted versions of all three shortly.

**Comment by vbongard** [comment]
@jaahmuhl @aflies1 

Here are the edits:

Vid 1, cut 3: https://drive.google.com/file/d/1azxc9UkOuOPvi176Y55gR4GE4ObRfJ6Y/view?usp=sharing

Vid 2, cut 3: https://drive.google.com/file/d/1bUd4komXFCFAPRaqCvQDNW4A8xFqb0lq/view?usp=sharing

Vid 3, cut 3: https://drive.google.com/file/d/13Ud6gIBldKK9XCQoio71Rdgeb0Bt7a40/view?usp=sharing

**Comment by jaahmuhl** [comment]
@vbongard  just a couple quick last edits.

![KKR Video 2 Cut 3.png](https://images.zenhubusercontent.com/5cb3b35dd74bd07972cea86e/75ceb770-afa4-4588-bc96-ec14da85fab5)

![KKR Video 3 Cut 3.png](https://images.zenhubusercontent.com/5cb3b35dd74bd07972cea86e/359b7d73-8a8e-49c1-88c8-29cad596ebc5)

**Comment by vbongard** [comment]
@jaahmuhl 

Here is video 2 with the updated caption: https://drive.google.com/file/d/1oIbti5KOdCnqBfRKzRcWBXm4W4Xzu0YT/view?usp=sharing

You can't change thumbnails in Google Drive, so instead I lengthened the outro by a few seconds, which should theoretically change the thumbnail (I can't check because the video is still processing). Here's the link for that: https://drive.google.com/file/d/1oIbti5KOdCnqBfRKzRcWBXm4W4Xzu0YT/view?usp=sharing

**Comment by jaahmuhl** [comment]
@mikepromazo 

Blurb:

There are a lot of smart people. There are not a lot of people who get things done. This is the simple secret, according to (Emilia Sherifova) from (KKR), to how to build a successful career.


Interview with: (Brett Hummel) & (Baptiste Bouvier)
Video Editor: (Victoria Bongard)

#secrettosuccess, #promazoexecinterviews, #1stjob, #howtosucceedinlife, #youngprofessional
