### ISSUE TITLE
Melisa Tokmak, Head of Document Products, ScaleAI

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#25]

**Comment by jaahmuhl** [comment]
https://drive.google.com/drive/folders/1z_w7lLHgketfkQgnYrveSKYgn195nt0q?usp=sharing

@aflies1

**Comment by vbongard** [comment]
Pitch: 

**Video 1: Industry Exploration**
_This video would cover advice about navigating the job search and tech industry. It focuses on specific types of roles (software engineering and project management), as well as keys to success and how to find a role and a company that suits you._ 
3:38 - difference between software engineering and project management, and what skills do students need to succeed in either role? (4:03 - 4:10, tech issues). Both are in demand, though project management is more tricky and strategy/vision. Good answer. She then gets into the importance of exploration and ends 8:15. Medium
13:20 - How can students understand what startups are really like? (answer 14:00) Ask questions during the interview process, especially why they chose the company they work for and push them on that. Also, go in person. Be the difficult candidate. Brett at 19:19, overall ends 20:51. Good, especially on how to do the interview process, focus on that rather than just startups

**Video 2: Advice For Immigrants**
_This would be a one-off video offering her advice for immigrant students_
28:02 - do you have any tips or suggestions for students that are immigrants? Answer begins 28:39. This industry is open to immigrants but it’s still more difficult for immigrants and it can be different depending on the company. Brett at 31:33, overall ends 33:52. Good for immigrant students! Could be good one-off


Full notes: https://docs.google.com/document/d/1EQvuDUgDkKj-nfHOrym-rPOSyez7CNaBeyxcWBgIREk/edit?usp=sharing

**Comment by jaahmuhl** [comment]
@mikepromazo @vbongard 

Yep this looks good. We had highlighted the same parts of the interview for our videos.

Thanks Victoria.

Brett

**Comment by vbongard** [comment]
Video 1, cut 1: https://drive.google.com/file/d/1LyYKkxEx_7pqswKyhwKHAYGFlU3lyDqS/view?usp=sharing

Video 2, cut 2: https://drive.google.com/file/d/1alEL-B8idJ9WrauOGpTogJkHLwfE54hB/view?usp=sharing

@jaahmuhl 
@mikepromazo

**Comment by jaahmuhl** [comment]
@mikepromazo 

Post this one: https://drive.google.com/file/d/1LyYKkxEx_7pqswKyhwKHAYGFlU3lyDqS/view?usp=sharing

Blurb:

"Be a difficult candidate". Hear the tips (Melisa Tokmak) from (ScaleAI) suggests you use to find out if the job is the right fit for you.

Interviewer: (Brett Hummel)
Editor: (Victoria Bongard)

#interview, #companyculture, #promazoexecinterviews,

**Comment by mikepromazo** [comment]
@jaahmuhl - The video is longer than 10 mins so we can't post on LI.  Did Victoria make a shorter cut we can use?

**Comment by jaahmuhl** [comment]
@mikepromazo I don't think so. I guess you can have her shorten it by 40 seconds.

**Comment by jaahmuhl** [comment]
@vbongard this is a great job on the video Victoria. It is awesome!

**Comment by mikepromazo** [comment]
@vbongard - Hi Victoria the team ran into an issue trying to post the video on LinkedIn as the length limit is 10 minutes.  Can you make another version and trim it down to <10 mins?

**Comment by vbongard** [comment]
Sure thing! Here's a shortened version: https://drive.google.com/file/d/1_jscnigcLNnLFUXxHpy9D00usBZBqak5/view?usp=sharing
